apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
    name: orders
    namespace: openfaas-fn
spec:
  metric:
    responseTime: 300m
  defaultResources:
    cpu: "1000m"
    memory: 1000Mi
  minResources:
    memory: 1000Mi
    cpu: 300m
  maxResources:
    memory: 1000Mi
    cpu: 20000m
  service:
    container: orders
    selector:
      matchLabels:
        name: orders
