apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
    name: orders
    namespace: openfaas-fn
spec:
  integralGain: 3
  proportionalGain: 6
  metric:
    responseTime: 300m
  defaultResources:
    cpu: "600m"
    memory: 1500Mi
  minResources:
    memory: 1500Mi
    cpu: 30m
  maxResources:
    memory: 1500Mi
    cpu: 20000m
  service:
    container: orders
    selector:
      matchLabels:
        name: orders
