apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
    name: payment
    namespace: openfaas-fn
spec:
  integralGain: 3
  proportionalGain: 6
  metric:
    responseTime: 100m
  defaultResources:
    cpu: "50"
    memory: 250Mi
  minResources:
    memory: 250Mi
    cpu: 30m
  maxResources:
    memory: 250Mi
    cpu: 20000m
  service:
    container: payment
    selector:
      matchLabels:
        name: payment
