apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
    name: user-register
    namespace: openfaas-fn
spec:
  metric:
    responseTime: 50m
  defaultResources:
    cpu: "1000m"
    memory: 1000Mi
  minResources:
    memory: 1000Mi
    cpu: 50m
  maxResources:
    memory: 1000Mi
    cpu: 20000m
  service:
    container: user-register
    selector:
      matchLabels:
        name: user-register
