apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
    name: user-login
    namespace: openfaas-fn
spec:
  integralGain: 3
  proportionalGain: 6
  metric:
    responseTime: 100m
  defaultResources:
    cpu: "50m"
    memory: 500Mi
  minResources:
    memory: 500Mi
    cpu: 30m
  maxResources:
    memory: 500Mi
    cpu: 20000m
  service:
    container: user-login
    selector:
      matchLabels:
        name: user-login
