apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-autoscaler:api-server
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-autoscaler:api-server
subjects:
- kind: User
  name: kube-apiserver
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edge-autoscaler:api-server
  apiGroup: rbac.authorization.k8s.io
