apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: carts
  namespace: openfaas-fn
spec:
  name: carts
  image: weaveworksdemos/carts:0.4.8
  environment:
    JAVA_OPTS: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false -Dserver.port=8080"
  limits:
    cpu: "300m"
    memory: "1024Mi"
  requests:
    cpu: "300m"
    memory: "1024Mi"