---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: openfaas-fn
spec:
  selector:
    app: front-end
#    edgeautoscaler.polimi.it/function-name: "front-end"
#    edgeautoscaler.polimi.it/function-namespace: "openfaas-fn"
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: front-end
  namespace: openfaas-fn
  labels:
    app: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      automountServiceAccountToken: true
      containers:
        - name: front-end
          image: systemautoscaler/front-end:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 1
            limits:
              memory: 128Mi
              cpu: 1
