apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    com.openfaas.function.spec: '{"name":"catalogue","image":"systemautoscaler/catalogue:dev","annotations":{"com.openfaas.health.http.initialDelay":"5m","com.openfaas.health.http.path":"/health"},"labels":{"com.openfaas.scale.max":"10","com.openfaas.scale.min":"0","com.openfaas.scale.zero":"true"},"limits":{"memory":"500Mi","cpu":"50m"},"requests":{"memory":"500Mi","cpu":"50m"},"readOnlyRootFilesystem":false}'
    com.openfaas.health.http.initialDelay: 5s
    com.openfaas.health.http.path: /health
    prometheus.io.scrape: "true"
  name: catalogue
  namespace: openfaas-fn
  selfLink: /apis/apps/v1/namespaces/openfaas-fn/deployments/catalogue
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      controller: catalogue
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        com.openfaas.function.spec: '{"name":"catalogue","image":"systemautoscaler/catalogue:dev","annotations":{"com.openfaas.health.http.initialDelay":"5m","com.openfaas.health.http.path":"/health"},"labels":{"com.openfaas.scale.max":"10","com.openfaas.scale.min":"0","com.openfaas.scale.zero":"true"},"limits":{"memory":"500Mi","cpu":"50m"},"requests":{"memory":"500Mi","cpu":"50m"},"readOnlyRootFilesystem":false}'
        com.openfaas.health.http.initialDelay: 5s
        com.openfaas.health.http.path: /health
        prometheus.io.scrape: "false"
      creationTimestamp: null
      labels:
        app: catalogue
        com.openfaas.scale.max: "10"
        com.openfaas.scale.min: "1"
        com.openfaas.scale.zero: "true"
        controller: catalogue
        faas_function: catalogue
    spec:
      containers:
        - image: systemautoscaler/catalogue:openfaas-dev
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 1000
            httpGet:
              path: /health
              port: 7777
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          name: catalogue
          ports:
            - containerPort: 7777
              protocol: TCP
          readinessProbe:
            failureThreshold: 1000
            httpGet:
              path: /health
              port: 7777
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: http-metrics
          image: systemautoscaler/http-metrics:openfaas-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ADDRESS
              value: "localhost"
            - name: APP_PORT
              value: "7777"
            - name: WINDOW_SIZE
              value: "30s"
            - name: WINDOW_GRANULARITY
              value: "1ms"
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FUNCTION
              value: "catalogue"
            - name: COMMUNITY
              value: "none"
            - name: NAMESPACE
              value: "openfaas-fn"
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 50m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
