apiVersion: v1
kind: Service
metadata:
  name: carts-get
  labels:
    app: carts-get
  namespace: openfaas-fn
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: carts-get
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"

