apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
  namespace: openfaas-fn
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    app: orders
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"

