apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
  namespace: openfaas-fn
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    app: user
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"


