apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-monitoring
  namespace: kube-system
  labels:
    app: cpu-monitoring
spec:
  selector:
    matchLabels:
      app: cpu-monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app: cpu-monitoring
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      automountServiceAccountToken: true
      serviceAccountName: cpu-monitoring
      containers:
        - name: cpu-monitoring
          image: systemautoscaler/cpu-monitoring:dev
          imagePullPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cpu-monitoring
  namespace: kube-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cpu-monitoring
roleRef:
  kind: ClusterRole
  name: cpu-monitoring
  apiGroup: "rbac.authorization.k8s.io"
subjects:
  - kind: ServiceAccount
    name: cpu-monitoring
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-monitoring
  namespace: kube-system
automountServiceAccountToken: false
