apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cpu-monitoring
  namespace: kube-system
  labels:
    app: cpu-monitoring
spec:
  selector:
    matchLabels:
      app: cpu-monitoring
  template:
    metadata:
      labels:
        app: cpu-monitoring
    spec:
      nodeSelector:
        edgeautoscaler.polimi.it/node: worker
      automountServiceAccountToken: true
      serviceAccountName: cpu-monitoring
      containers:
        - name: cpu-monitoring
          image: systemautoscaler/cpu-monitoring:dev
          imagePullPolicy: Always
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cpu-monitoring
  namespace: kube-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cpu-monitoring
roleRef:
  kind: ClusterRole
  name: cpu-monitoring
  apiGroup: "rbac.authorization.k8s.io"
subjects:
  - kind: ServiceAccount
    name: cpu-monitoring
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-monitoring
  namespace: kube-system
automountServiceAccountToken: false
