apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: delay-discovery
  namespace: default
  labels:
    app: delay-discovery
spec:
  selector:
    matchLabels:
      app: delay-discovery
  template:
    metadata:
      labels:
        app: delay-discovery
    spec:
      automountServiceAccountToken: true
      serviceAccountName: delay-discovery
      containers:
        - name: delay-discovery
          image: systemautoscaler/delay-discovery
          imagePullPolicy: Always
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

