apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-database
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: metrics-database
  replicas: 1
  template:
    metadata:
      labels:
        app: metrics-database
    spec:
      containers:
        - name: metrics-database
          image: systemautoscaler/database:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-database
  namespace: kube-system
  labels:
    app: metrics-database
spec:
  ports:
    - port: 5432
  selector:
    app: metrics-database
