---
apiVersion: v1
kind: Service
metadata:
  name: carts-post
  labels:
    name: carts-post
  namespace: openfaas-fn
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    edgeautoscaler.polimi.it/function-name: "carts-post"
    edgeautoscaler.polimi.it/function-namespace: "openfaas-fn"
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"

