apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: catalogue
  namespace: openfaas-fn
spec:
  labels:
    com.openfaas.scale.max: "0"
    com.openfaas.scale.min: "0"
    com.openfaas.scale.zero: "true"
  name: catalogue
  image: systemautoscaler/catalogue:dev
  limits:
    cpu: "50m"
    memory: "100Mi"
  requests:
    cpu: "50m"
    memory: "100Mi"

