apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: front-end
  namespace: openfaas-fn
  labels:
    app: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: systemautoscaler/front-end:dev
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2
              memory: 150Mi
            requests:
              cpu: 2
              memory: 150Mi
