---
apiVersion: v1
kind: Service
metadata:
  name: user-login
  labels:
    name: user-login
  namespace: openfaas-fn
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8000
  selector:
    edgeautoscaler.polimi.it/function-name: "user-login"
    edgeautoscaler.polimi.it/function-namespace: "openfaas-fn"
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"


